### ISSUE TITLE
When I start the script I get this traceback

### ISSUE THREAD

**Issue by Baccount** [mikeperry-tor/vanguards#1]
```
User-MacBook-Pro:vanguards-master UserUser$ ./src/vanguards.py
NOTICE[Fri May 25 16:19:22 2018]: Creating new vanguard state file at: vanguards.state
NOTICE[Fri May 25 16:19:22 2018]: Connected to Tor version 0.3.3.6 (git-7dd0813e783ae16e)
Traceback (most recent call last):
  File "./src/vanguards.py", line 8, in <module>
    vanguards.main.main()
  File "/Users/UserUser/Desktop/vanguards-master/src/vanguards/main.py", line 57, in main
    state.new_consensus_event(controller, None)
  File "/Users/UserUser/Desktop/vanguards-master/src/vanguards/vanguards.py", line 86, in new_consensus_event
    "cached-microdesc-consensus")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by mikeperry-tor** [comment]
It looks like if DataDirectory is not set in your torrc, Tor will not report the directory it chose to the control port.

The best I can do is emit an error message that makes it clear that you must set DataDirectory in the torrc. Does commit ac1a2c5183cbe02216d38eb47a0a66f710fe33de do this for you?
