### ISSUE TITLE
Please catch CTRL+c and quit

### ISSUE THREAD

**Issue by traumschule** [mikeperry-tor/vanguards#30]
On CTRL+c this fills my screen:
```
Please catch CTRL+c and quit
Traceback (most recent call last):
  File "./src/vanguards.py", line 8, in <module>
    vanguards.main.main()
  File "/media/src/tor/vanguards/src/vanguards/main.py", line 55, in main
    ret = control_loop(state)
  File "/media/src/tor/vanguards/src/vanguards/main.py", line 156, in control_loop
    time.sleep(1)
KeyboardInterrupt
Exception in thread Tor Listener (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/lib/python2.7/dist-packages/stem/control.py", line 952, in _reader_loop
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'ControllerError'
```
Please catch the interrupt and exit with "Have a nice day!" or similar :)

**Comment by mikeperry-tor** [comment]
Ok I pushed a commit to origin/master to do this.

**Comment by mikeperry-tor** [comment]
v0.2.2 is released, closing this.
