### ISSUE TITLE
Error when trying to run vanguards

### ISSUE THREAD

**Issue by exploreexplo** [mikeperry-tor/vanguards#39]
Find error message bellow;

```
    if p[0] == "$":
IndexError: string index out of range
```
Thanks

**Comment by mikeperry-tor** [comment]
Can you give the full error message along with how you invoked vanguards?

**Comment by exploreexplo** [comment]
I solved that problem by using this `p.startswith('$')` instead of this `if p[0] == "$":`
I invoked vanguard like this `./src/vanguards.py` from the cloned directory

**Comment by mikeperry-tor** [comment]
These lines are not present in ./src/vanguards.py. I do not know what you are editing. You need to paste complete error messages (they are multiple lines).

**Comment by mikeperry-tor** [comment]
I suspect this user was trying to run vanguards from a non-standard directory. Closing.

**Comment by exploreexplo** [comment]
Bellow is the error I get when I run vanguards

```
petertest@host2345007765:~/vanguards$ sudo ./src/vanguards.py
NOTICE[Wed Apr 24 11:34:57 2019]: Creating new vanguard state file at: vanguards.state
NOTICE[Wed Apr 24 11:34:57 2019]: Vanguards 0.3.1 connected to Tor 0.3.5.8 using stem 1.4.1
Traceback (most recent call last):
  File "./src/vanguards.py", line 8, in <module>
    vanguards.main.main()
  File "/home/testproject/vanguards/src/vanguards/main.py", line 22, in main
    run_main()
  File "/home/testproject/vanguards/src/vanguards/main.py", line 61, in run_main
    ret = control_loop(state)
  File "/home/testproject/vanguards/src/vanguards/main.py", line 98, in control_loop
    state.new_consensus_event(controller, None)
  File "/home/testproject/vanguards/src/vanguards/vanguards.py", line 206, in new_consensus_event
    exclude_nodes = ExcludeNodes(controller)
  File "/home/testproject/vanguards/src/vanguards/vanguards.py", line 60, in __init__
    self._parse_line(controller.get_conf("ExcludeNodes"))
  File "/home/testproject/vanguards/src/vanguards/vanguards.py", line 75, in _parse_line
    if p[0] == "$":
IndexError: string index out of range

```
