### ISSUE TITLE
Directory /tmp/onionsvc.d/data/osdir cannot be read: Operation not permitted

### ISSUE THREAD

**Issue by toralf** [mikeperry-tor/vanguards#57]
Creating an onion service (no concerns from my side wrt to address/ports - just I like to play with) using https://github.com/toralf/torutils/blob/master/os.sh and the current git tree v0.3.1-10-g6dd476f gives
```
nice /opt/torutils/os.sh tinderbox.zwiebeltoralf.de 31556
~torproject/vanguards/src/vanguards.py --control_port 9099
NOTICE[Sun Jul 12 13:12:41 2020]: Vanguards 0.3.1 connected to Tor 0.4.4.2-alpha using stem 1.8.0
Traceback (most recent call last):
  File "/home/torproject/vanguards/src/vanguards.py", line 8, in <module>
    vanguards.main.main()
  File "/home/torproject/vanguards/src/vanguards/main.py", line 22, in main
    run_main()
  File "/home/torproject/vanguards/src/vanguards/main.py", line 61, in run_main
    ret = control_loop(state)
  File "/home/torproject/vanguards/src/vanguards/main.py", line 98, in control_loop
    state.new_consensus_event(controller, None)
  File "/home/torproject/vanguards/src/vanguards/vanguards.py", line 225, in new_consensus_event
    self.configure_tor(controller)
  File "/home/torproject/vanguards/src/vanguards/vanguards.py", line 240, in configure_tor
    controller.set_conf("NumEntryGuards", str(NUM_LAYER1_GUARDS))
  File "/usr/lib/python3.7/site-packages/stem/control.py", line 2473, in set_conf
    self.set_options({param: value}, False)
  File "/usr/lib/python3.7/site-packages/stem/control.py", line 2567, in set_options
    raise stem.InvalidRequest(response.code, response.message)
stem.InvalidRequest: Unacceptable option value: Failed to configure rendezvous options. See logs for details.
```
and the debug log of that onion service gives
```
Jul 12 13:12:41.000 [debug] conn_read_callback(): socket 17 wants to read.
Jul 12 13:12:41.000 [debug] read_to_chunk(): Read 16 bytes. 16 on inbuf.
Jul 12 13:12:41.000 [debug] conn_write_callback(): socket 17 wants to write.
Jul 12 13:12:41.000 [debug] circuit_get_open_circ_or_launch(): one on the way!
Jul 12 13:12:41.000 [debug] circuit_remove_handled_ports(): Port 443 is already being handled; removing.
Jul 12 13:12:42.000 [debug] conn_read_callback(): socket 17 wants to read.
Jul 12 13:12:42.000 [debug] read_to_chunk(): Read 28 bytes. 28 on inbuf.
Jul 12 13:12:42.000 [debug] parse_addr_policy(): Adding new entry 'reject *4:*'
Jul 12 13:12:42.000 [debug] parse_addr_policy(): Adding new entry 'reject *6:*'
Jul 12 13:12:42.000 [info] config_generic_service(): HiddenServiceDir="/tmp/onionsvc.d/data/osdir". Configuring...
Jul 12 13:12:42.000 [info] config_generic_service(): HiddenServicePort=80 tinderbox.zwiebeltoralf.de:31556 for "/tmp/onionsvc.d/data/osdir"
Jul 12 13:12:42.000 [warn] Directory /tmp/onionsvc.d/data/osdir cannot be read: Operation not permitted
Jul 12 13:12:42.000 [warn] Controller gave us config lines that didn't validate: Failed to configure rendezvous options. See logs for details.
Jul 12 13:12:42.000 [debug] conn_write_callback(): socket 17 wants to write.
Jul 12 13:12:42.000 [debug] conn_read_callback(): socket 17 wants to read.
Jul 12 13:12:42.000 [debug] read_to_chunk(): Encountered eof on fd 17
Jul 12 13:12:42.000 [info] connection_control_reached_eof(): Control connection reached EOF. Closing.
Jul 12 13:12:42.000 [debug] conn_close_if_marked(): Cleaning up connection (fd 17).
Jul 12 13:12:42.000 [debug] connection_remove(): removing socket 17 (type Control), n_conns now 10
Jul 12 13:12:42.000 [debug] connection_free_minimal(): closing fd 17.
Jul 12 13:12:42.000 [debug] circuit_get_open_circ_or_launch(): one on the way!
```

**Comment by mikeperry-tor** [comment]
This seems like Tor itself does not have permission to its datadir for the onion service you configured. Make sure the user that Tor runs under can read that dir.

Pretty sure that's the issue here, and not a vanguards bug, so I'm closing this.
